#!/bin/bash

# Find and Replace Script
# Usage: ./find_replace.sh /path/to/directory "search_string" "replace_string"

TARGET_DIR=$1
SEARCH_STRING=$2
REPLACE_STRING=$3

if [ -z "$TARGET_DIR" ] || [ -z "$SEARCH_STRING" ] || [ -z "$REPLACE_STRING" ]; then
    echo "Usage: $0 /path/to/directory \"search_string\" \"replace_string\""
    exit 1
fi

find "$TARGET_DIR" -type f -exec sed -i "s/$SEARCH_STRING/$REPLACE_STRING/g" {} +

echo "Find and replace completed in $TARGET_DIR"
